apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: jpetstore
  namespace: jpet-project
  labels:
    app: jpetstore
spec:
  selector:
    matchLabels:
      app: jpetstore
  componentKinds:
  - group: app.ibm.com
    kind: Subscription
