kind: Deployment
apiVersion: apps/v1
metadata:
  name: jpetstoreweb
spec:
  replicas: 1
  selector:
      matchLabels:
        app: jpetstoreweb
  template:
    metadata:
      labels:
        app: jpetstoreweb
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: jpetstoreweb
        image: quay.io/jmlafont/jpetstore-web
        env:
          - name: VERSION
            value: "1"
        ports:
        - containerPort: 9080
        readinessProbe:
          httpGet:
            path: /
            port: 9080
          initialDelaySeconds: 10
          periodSeconds: 5
---
kind: Service
apiVersion: v1
metadata:
  name: web
spec:
  selector:
    app: jpetstoreweb
  ports:
  - port: 80
    targetPort: 9080
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: jpetstoredb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jpetstoredb
  template:
    metadata:
      labels:
        app: jpetstoredb
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: jpetstoredb
        image: quay.io/jmlafont/jpetstore-db
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: "foobar"
          - name: MYSQL_DATABASE
            value: "jpetstore"
          - name: MYSQL_USER
            value: "jpetstore"
          - name: MYSQL_PASSWORD
            value: "foobar"
---
kind: Service
apiVersion: v1
metadata:
  name: db
spec:
  selector:
    app: jpetstoredb
  ports:
  - port: 3306
    targetPort: 3306
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: jpetstore
spec:
  port:
    targetPort: 9080
  to:
    kind: Service
    name: web
    weight: 100
  wildcardPolicy: None

